# fazer com que o pull request rode todos os testes
# se ok, quero aceitar o pullRequest. Caso contrário, vai falhar

name: Pull request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envKey_POSTGRES_USER: ${{secrets.POSTGRES_PASSWORD}}
          envKey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_USER}}
          envKey_POSTGRES_DB: "PFAC-DB-tests"
          envKey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run node_app_github-ci npm run test